name: Daily Poll Monitor

on:
  schedule:
    # Ежедневно в 12:00 UTC = 15:00 MSK
    - cron: '0 12 * * *'
    # Ежедневно в 00:00 UTC = 03:00 MSK
    - cron: '0 0 * * *'
  workflow_dispatch:
    inputs:
      action:
        description: 'Действие для выполнения'
        required: true
        default: 'monitor'
        type: choice
        options:
        - monitor
        - test

jobs:
  daily-monitor:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Restore poll votes cache
      uses: actions/cache@v3
      with:
        path: |
          poll_votes_*.json
        key: poll-votes-${{ github.ref }}
        restore-keys: |
          poll-votes-
        
    - name: Check poll votes files
      run: |
        echo "🔍 ПРОВЕРКА ФАЙЛОВ ГОЛОСОВАНИЙ"
        echo "=================================================="
        echo "📋 Проверяем наличие файлов голосований:"
        ls -la poll_votes_*.json 2>/dev/null || echo "ℹ️ Файлы голосований не найдены (это нормально для первого запуска)"
        echo "=================================================="
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install python-telegram-bot gspread google-auth python-dotenv
        
    - name: Create .env file
      run: |
        echo "BOT_TOKEN=${{ secrets.BOT_TOKEN }}" >> .env
        echo "CHAT_ID=${{ secrets.CHAT_ID }}" >> .env
        echo "GOOGLE_SHEETS_CREDENTIALS=${{ secrets.GOOGLE_SHEETS_CREDENTIALS }}" >> .env
        echo "SPREADSHEET_ID=${{ secrets.SPREADSHEET_ID }}" >> .env
        
    - name: Run Daily Poll Monitor
      env:
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        CHAT_ID: ${{ secrets.CHAT_ID }}
        GOOGLE_SHEETS_CREDENTIALS: ${{ secrets.GOOGLE_SHEETS_CREDENTIALS }}
        SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}
      run: |
        echo "🕐 Запуск ежедневного мониторинга голосований..."
        echo "🕐 Время запуска: $(date)"
        echo "📅 День недели: $(date +%u)"
        echo "📅 День недели (название): $(date +%A)"
        echo "ℹ️ Проверка проводится 2 раза в день: 15:00 и 03:00 по Москве"
        
        # Проверяем переменные окружения
        if [ -z "$BOT_TOKEN" ]; then
          echo "❌ BOT_TOKEN не настроен"
          exit 1
        fi
        if [ -z "$CHAT_ID" ]; then
          echo "❌ CHAT_ID не настроен"
          exit 1
        fi
        if [ -z "$GOOGLE_SHEETS_CREDENTIALS" ]; then
          echo "❌ GOOGLE_SHEETS_CREDENTIALS не настроен"
          exit 1
        fi
        if [ -z "$SPREADSHEET_ID" ]; then
          echo "❌ SPREADSHEET_ID не настроен"
          exit 1
        fi
        
        echo "✅ Все переменные окружения настроены"
        echo "🔄 Запуск ежедневного мониторинга..."
        echo "=================================================="
        
        # Запускаем ежедневный мониторинг
        echo "📊 Запуск ежедневного мониторинга голосований..."
        python daily_poll_monitor.py
        
        echo "=================================================="
        echo "Завершение работы мониторинга"
        
    - name: Check files before cache
      run: |
        echo "🔍 ПРОВЕРКА ФАЙЛОВ ПЕРЕД СОХРАНЕНИЕМ В CACHE"
        echo "=================================================="
        if ls poll_votes_*.json 1> /dev/null 2>&1; then
          echo "✅ Файлы голосований найдены:"
          ls -la poll_votes_*.json
        else
          echo "ℹ️ Файлы голосований не найдены"
        fi
        echo "=================================================="
        
    - name: Save poll votes cache
      uses: actions/cache@v3
      if: always()
      with:
        path: |
          poll_votes_*.json
        key: poll-votes-${{ github.ref }}
        
    - name: Upload logs
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: daily-monitor-logs
        path: |
          poll_votes_*.json
          *.log
        retention-days: 7