name: Daily Poll Monitor

on:
  schedule:
    # Ежедневный мониторинг с понедельника по субботу
    # 2 проверки в день: утром и вечером
    # Утром: 08:00-08:45 UTC = 11:00-11:45 MSK
    - cron: '0,15,30,45 8 * * 1-6'  # Понедельник-суббота
    # Вечером: 20:00-20:45 UTC = 23:00-23:45 MSK  
    - cron: '0,15,30,45 20 * * 1-6'  # Понедельник-суббота
  workflow_dispatch:
    inputs:
      action:
        description: 'Действие для выполнения'
        required: true
        default: 'monitor'
        type: choice
        options:
        - monitor
        - check_tuesday
        - check_thursday
        - check_friday

jobs:
  daily-poll-monitor:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Restore poll monitor cache
      uses: actions/cache@v3
      with:
        path: |
          poll_monitor_history.json
          poll_changes_log.json
          poll_votes_*.json
        key: poll-monitor-${{ github.ref }}
        restore-keys: |
          poll-monitor-
        
    - name: Check poll monitor files
      run: |
        echo "🔍 ПРОВЕРКА ФАЙЛОВ МОНИТОРИНГА ОПРОСОВ"
        echo "=================================================="
        echo "📋 Проверяем наличие файлов:"
        ls -la *.json 2>/dev/null || echo "❌ JSON файлы не найдены"
        echo ""
        echo "📄 Содержимое poll_monitor_history.json (если есть):"
        if [ -f "poll_monitor_history.json" ]; then
          cat poll_monitor_history.json
        else
          echo "❌ Файл poll_monitor_history.json не найден"
        fi
        echo ""
        echo "📄 Содержимое poll_changes_log.json (если есть):"
        if [ -f "poll_changes_log.json" ]; then
          cat poll_changes_log.json
        else
          echo "❌ Файл poll_changes_log.json не найден"
        fi
        echo "=================================================="
        
    - name: Initialize poll monitor files
      run: |
        echo "🔧 ИНИЦИАЛИЗАЦИЯ ФАЙЛОВ МОНИТОРИНГА ОПРОСОВ"
        echo "=================================================="
        # Создаем пустые файлы, если они не существуют
        if [ ! -f "poll_monitor_history.json" ]; then
          echo "📝 Создаем пустой poll_monitor_history.json"
          echo '{}' > poll_monitor_history.json
        fi
        if [ ! -f "poll_changes_log.json" ]; then
          echo "📝 Создаем пустой poll_changes_log.json"
          echo '{"changes": []}' > poll_changes_log.json
        fi
        echo "✅ Файлы мониторинга инициализированы"
        echo "=================================================="
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install python-telegram-bot gspread google-auth python-dotenv
        
    - name: Create .env file
      run: |
        echo "BOT_TOKEN=${{ secrets.BOT_TOKEN }}" >> .env
        echo "CHAT_ID=${{ secrets.CHAT_ID }}" >> .env
        echo "ANNOUNCEMENTS_TOPIC_ID=${{ secrets.ANNOUNCEMENTS_TOPIC_ID }}" >> .env
        echo "GOOGLE_SHEETS_CREDENTIALS=${{ secrets.GOOGLE_SHEETS_CREDENTIALS }}" >> .env
        echo "SPREADSHEET_ID=${{ secrets.SPREADSHEET_ID }}" >> .env
        
    - name: Run Daily Poll Monitor
      env:
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        CHAT_ID: ${{ secrets.CHAT_ID }}
        ANNOUNCEMENTS_TOPIC_ID: ${{ secrets.ANNOUNCEMENTS_TOPIC_ID }}
        GOOGLE_SHEETS_CREDENTIALS: ${{ secrets.GOOGLE_SHEETS_CREDENTIALS }}
        SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}
      run: |
        echo "🔍 Запуск ежедневного мониторинга опросов..."
        echo "🕐 Время запуска: $(date)"
        echo "📅 День недели: $(date +%u)"
        
        # Проверяем переменные окружения
        if [ -z "$BOT_TOKEN" ]; then
          echo "❌ BOT_TOKEN не настроен"
          exit 1
        fi
        if [ -z "$CHAT_ID" ]; then
          echo "❌ CHAT_ID не настроен"
          exit 1
        fi
        if [ -z "$GOOGLE_SHEETS_CREDENTIALS" ]; then
          echo "❌ GOOGLE_SHEETS_CREDENTIALS не настроен"
          exit 1
        fi
        if [ -z "$SPREADSHEET_ID" ]; then
          echo "❌ SPREADSHEET_ID не настроен"
          exit 1
        fi
        
        echo "✅ Все переменные окружения настроены"
        echo "🔄 Запуск ежедневного мониторинга опросов..."
        echo "=================================================="
        
        # Запускаем ежедневный мониторинг
        echo "🔍 Запуск ежедневного мониторинга опросов..."
        python daily_poll_monitor.py
        
        echo "=================================================="
        echo "Завершение работы мониторинга"
        
    - name: Check files before cache
      run: |
        echo "🔍 ПРОВЕРКА ФАЙЛОВ ПЕРЕД СОХРАНЕНИЕМ В CACHE"
        echo "=================================================="
        if [ -f "poll_monitor_history.json" ]; then
          echo "✅ poll_monitor_history.json существует"
        else
          echo "❌ poll_monitor_history.json не существует"
        fi
        if [ -f "poll_changes_log.json" ]; then
          echo "✅ poll_changes_log.json существует"
        else
          echo "❌ poll_changes_log.json не существует"
        fi
        echo "=================================================="
        
    - name: Save poll monitor cache
      uses: actions/cache@v3
      if: always()
      with:
        path: |
          poll_monitor_history.json
          poll_changes_log.json
          poll_votes_*.json
        key: poll-monitor-${{ github.ref }}
        
    - name: Upload logs
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: poll-monitor-logs
        path: |
          *.json
          *.log
        retention-days: 7