name: Game System Manager - Test Mode

on:
  workflow_dispatch: # Только ручной запуск для тестирования

jobs:
  run-game-system-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Restore history from cache
      uses: actions/cache@v3
      with:
        path: |
          game_announcements.json
          game_polls_history.json
        key: game-history-test-${{ github.ref }}
        restore-keys: |
          game-history-test-
      
    - name: Check restored history
      run: |
        echo "🔍 ПРОВЕРКА ВОССТАНОВЛЕННОЙ ИСТОРИИ (ТЕСТ)"
        echo "=================================================="
        echo "📋 Содержимое рабочей директории:"
        ls -la
        echo ""
        echo "📋 Содержимое всех JSON файлов:"
        find . -name "*.json" -type f
        echo "=================================================="
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-github.txt
        
    - name: Initialize history files
      run: |
        echo "🔧 ИНИЦИАЛИЗАЦИЯ ФАЙЛОВ ИСТОРИИ (ТЕСТ)"
        echo "=================================================="
        # Создаем пустые файлы истории, если они не существуют
        if [ ! -f "game_announcements.json" ]; then
          echo "📝 Создаем пустой game_announcements.json"
          echo '{}' > game_announcements.json
        fi
        if [ ! -f "game_polls_history.json" ]; then
          echo "📝 Создаем пустой game_polls_history.json"
          echo '{}' > game_polls_history.json
        fi
        echo "✅ Файлы истории инициализированы"
        echo "=================================================="
        
    - name: Run complete game system (TEST MODE)
      env:
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        CHAT_ID: ${{ secrets.CHAT_ID }}
        GAMES_TOPIC_ID: ${{ secrets.GAMES_TOPIC_ID }}
        TARGET_TEAMS: ${{ secrets.TARGET_TEAMS }}
        GOOGLE_SHEETS_CREDENTIALS: ${{ secrets.GOOGLE_SHEETS_CREDENTIALS }}
        SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}
        TEST_MODE: "true"  # ТЕСТОВЫЙ РЕЖИМ
      run: |
        echo "🧪 Запуск системы управления играми (ТЕСТОВЫЙ РЕЖИМ)..."
        echo "=================================================="
        python run_game_system.py
        echo "=================================================="
        echo "Завершение работы системы (ТЕСТ)"
        
    - name: Save history to cache
      uses: actions/cache@v3
      if: always()
      with:
        path: |
          game_announcements.json
          game_polls_history.json
        key: game-history-test-${{ github.ref }}
        
    - name: Upload logs
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: game-system-test-logs
        path: |
          game_polls_history.json
          game_announcements.json
          *.log
