name: Game Results Monitor

on:
  # schedule:
  #   # Запуск каждые 30 минут для проверки завершенных игр
  #   - cron: '*/30 * * * *'
  workflow_dispatch: # Позволяет запускать вручную

jobs:
  monitor_results:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-github.txt
        
    - name: Check secrets availability
      run: |
        echo "Checking secrets availability..."
        if [ -n "${{ secrets.BOT_TOKEN }}" ]; then
          echo "✅ BOT_TOKEN is available"
        else
          echo "❌ BOT_TOKEN is not available - workflow will fail"
        fi
        
        if [ -n "${{ secrets.CHAT_ID }}" ]; then
          echo "✅ CHAT_ID is available"
        else
          echo "❌ CHAT_ID is not available - workflow will fail"
        fi
        
        if [ -n "${{ secrets.TELEGRAM_API_ID }}" ]; then
          echo "✅ TELEGRAM_API_ID is available"
        else
          echo "⚠️ TELEGRAM_API_ID is not available, poll results will not be collected"
        fi
        
        if [ -n "${{ secrets.TELEGRAM_API_HASH }}" ]; then
          echo "✅ TELEGRAM_API_HASH is available"
        else
          echo "⚠️ TELEGRAM_API_HASH is not available, poll results will not be collected"
        fi
        
        if [ -n "${{ secrets.TELEGRAM_PHONE }}" ]; then
          echo "✅ TELEGRAM_PHONE is available"
        else
          echo "⚠️ TELEGRAM_PHONE is not available, poll results will not be collected"
        fi
        
    - name: Run Game Results Monitor
      env:
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        CHAT_ID: ${{ secrets.CHAT_ID }}
        TELEGRAM_API_ID: ${{ secrets.TELEGRAM_API_ID }}
        TELEGRAM_API_HASH: ${{ secrets.TELEGRAM_API_HASH }}
        TELEGRAM_PHONE: ${{ secrets.TELEGRAM_PHONE }}
      run: |
        # Проверяем наличие обязательных переменных
        if [ -z "$BOT_TOKEN" ]; then
          echo "❌ ОШИБКА: BOT_TOKEN не установлен в GitHub Secrets"
          echo "Добавьте BOT_TOKEN в Settings → Secrets and variables → Actions"
          exit 1
        fi
        
        if [ -z "$CHAT_ID" ]; then
          echo "❌ ОШИБКА: CHAT_ID не установлен в GitHub Secrets"
          echo "Добавьте CHAT_ID в Settings → Secrets and variables → Actions"
          exit 1
        fi
        
        # Проверяем финальные значения (скрываем токен)
        echo "BOT_TOKEN: ${BOT_TOKEN:0:10}..."
        echo "CHAT_ID: $CHAT_ID"
        
        # Проверяем наличие Python скрипта
        if [ ! -f "run_game_results_monitor.py" ]; then
          echo "❌ Файл run_game_results_monitor.py не найден"
          exit 1
        fi
        
        echo "Запуск мониторинга результатов игр..."
        python run_game_results_monitor.py
        
    - name: Handle errors
      if: failure()
      env:
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        CHAT_ID: ${{ secrets.CHAT_ID }}
      run: |
        echo "❌ GitHub Actions завершился с ошибкой"
        echo "Проверка доступности переменных для отправки уведомления об ошибке..."
        
        if [ -z "$BOT_TOKEN" ]; then
          echo "⚠️ BOT_TOKEN недоступен для отправки уведомления об ошибке"
          echo "Добавьте BOT_TOKEN в GitHub Secrets для получения уведомлений об ошибках"
        fi
        
        if [ -z "$CHAT_ID" ]; then
          echo "⚠️ CHAT_ID недоступен для отправки уведомления об ошибке"
          echo "Добавьте CHAT_ID в GitHub Secrets для получения уведомлений об ошибках"
        fi
        
        echo "Ошибки будут отправлены в основной чат через скрипт"
