name: Game Polls Creator

on:
  schedule:
    # Запускаем каждый день в 9:00 по московскому времени (6:00 UTC)
    - cron: '0 6 * * *'
  workflow_dispatch: # Позволяет запускать вручную

jobs:
  create-game-polls:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-github.txt
        
    - name: Create game polls
      env:
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        CHAT_ID: ${{ secrets.CHAT_ID }}
        GAMES_TOPIC_ID: ${{ secrets.GAMES_TOPIC_ID }}
        TARGET_TEAMS: ${{ secrets.TARGET_TEAMS }}
      run: |
        python run_game_polls.py
        
    - name: Upload logs
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: game-polls-logs
        path: |
          game_polls_history.json
          *.log
