name: PullUP Games Monitor

on:
  # schedule:
  #   # Запуск каждые 30 минут
  #   - cron: '*/30 * * * *'
  workflow_dispatch: # Позволяет запускать вручную

jobs:
  monitor:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-github.txt
        
    - name: Check secrets availability
      run: |
        echo "Checking secrets availability..."
        if [ -n "${{ secrets.BOT_TOKEN }}" ]; then
          echo "✅ BOT_TOKEN is available"
        else
          echo "❌ BOT_TOKEN is not available - workflow will fail"
        fi
        
        if [ -n "${{ secrets.CHAT_ID }}" ]; then
          echo "✅ CHAT_ID is available"
        else
          echo "❌ CHAT_ID is not available - workflow will fail"
        fi
        
        if [ -n "${{ secrets.TEST_CHAT_ID }}" ]; then
          echo "✅ TEST_CHAT_ID is available"
        else
          echo "⚠️ TEST_CHAT_ID is not available, will use default value"
        fi
        
    - name: Run PullUP monitor
      env:
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        CHAT_ID: ${{ secrets.CHAT_ID }}
        TEST_CHAT_ID: ${{ secrets.TEST_CHAT_ID }}
      run: |
        # Проверяем наличие обязательных переменных
        if [ -z "$BOT_TOKEN" ]; then
          echo "❌ ОШИБКА: BOT_TOKEN не установлен в GitHub Secrets"
          echo "Добавьте BOT_TOKEN в Settings → Secrets and variables → Actions"
          exit 1
        fi
        
        if [ -z "$CHAT_ID" ]; then
          echo "❌ ОШИБКА: CHAT_ID не установлен в GitHub Secrets"
          echo "Добавьте CHAT_ID в Settings → Secrets and variables → Actions"
          exit 1
        fi
        
        # Устанавливаем значение по умолчанию для TEST_CHAT_ID если оно не задано
        if [ -z "$TEST_CHAT_ID" ]; then
          echo "TEST_CHAT_ID не установлен, используем значение по умолчанию"
          export TEST_CHAT_ID="-15573582"
        fi
        
        # Проверяем финальные значения (скрываем токен)
        echo "BOT_TOKEN: ${BOT_TOKEN:0:10}..."
        echo "CHAT_ID: $CHAT_ID"
        echo "TEST_CHAT_ID: $TEST_CHAT_ID"
        
        # Проверяем наличие Python скрипта
        if [ ! -f "github_actions_monitor.py" ]; then
          echo "❌ Файл github_actions_monitor.py не найден"
          exit 1
        fi
        
        echo "Запуск монитора PullUP игр..."
        python github_actions_monitor.py
        
    - name: Handle errors
      if: failure()
      env:
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        TEST_CHAT_ID: ${{ secrets.TEST_CHAT_ID }}
      run: |
        echo "❌ GitHub Actions завершился с ошибкой"
        echo "Проверка доступности переменных для отправки уведомления об ошибке..."
        
        if [ -z "$BOT_TOKEN" ]; then
          echo "⚠️ BOT_TOKEN недоступен для отправки уведомления об ошибке"
          echo "Добавьте BOT_TOKEN в GitHub Secrets для получения уведомлений об ошибках"
        fi
        
        # Устанавливаем значение по умолчанию для TEST_CHAT_ID если оно не задано
        if [ -z "$TEST_CHAT_ID" ]; then
          export TEST_CHAT_ID="-15573582"
        fi
        
        echo "Ошибки будут отправлены в тестовый чат через скрипт"
