name: Training Polls

on:
  schedule:
    # Запуск каждый день в 07:00 UTC (10:00 по Москве) для создания опросов в воскресенье
    # и в 06:00 UTC (09:00 по Москве) для сбора данных в среду/субботу
    - cron: '0 6,7 * * *'
  workflow_dispatch: # Позволяет запускать вручную

jobs:
  training_polls:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-github.txt
        
    - name: Check secrets availability
      run: |
        echo "Checking secrets availability..."
        if [ -n "${{ secrets.BOT_TOKEN }}" ]; then
          echo "✅ BOT_TOKEN is available"
        else
          echo "❌ BOT_TOKEN is not available - workflow will fail"
        fi
        
        if [ -n "${{ secrets.CHAT_ID }}" ]; then
          echo "✅ CHAT_ID is available"
        else
          echo "❌ CHAT_ID is not available - workflow will fail"
        fi
        
        if [ -n "${{ secrets.GOOGLE_SHEETS_CREDENTIALS }}" ]; then
          echo "✅ GOOGLE_SHEETS_CREDENTIALS is available"
        else
          echo "❌ GOOGLE_SHEETS_CREDENTIALS is not available - workflow will fail"
        fi
        
        if [ -n "${{ secrets.SPREADSHEET_ID }}" ]; then
          echo "✅ SPREADSHEET_ID is available"
        else
          echo "❌ SPREADSHEET_ID is not available - workflow will fail"
        fi
        
        if [ -n "${{ secrets.ANNOUNCEMENTS_TOPIC_ID }}" ]; then
          echo "✅ ANNOUNCEMENTS_TOPIC_ID is available"
        else
          echo "⚠️ ANNOUNCEMENTS_TOPIC_ID is not available - using default (26)"
        fi
        
    - name: Run Training Polls (Creation)
      env:
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        CHAT_ID: ${{ secrets.CHAT_ID }}
        GOOGLE_SHEETS_CREDENTIALS: ${{ secrets.GOOGLE_SHEETS_CREDENTIALS }}
        SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}
        ANNOUNCEMENTS_TOPIC_ID: ${{ secrets.ANNOUNCEMENTS_TOPIC_ID }}
      run: |
        # Проверяем наличие обязательных переменных
        if [ -z "$BOT_TOKEN" ]; then
          echo "❌ ОШИБКА: BOT_TOKEN не установлен в GitHub Secrets"
          echo "Добавьте BOT_TOKEN в Settings → Secrets and variables → Actions"
          exit 1
        fi
        
        if [ -z "$CHAT_ID" ]; then
          echo "❌ ОШИБКА: CHAT_ID не установлен в GitHub Secrets"
          echo "Добавьте CHAT_ID в Settings → Secrets and variables → Actions"
          exit 1
        fi
        
        if [ -z "$GOOGLE_SHEETS_CREDENTIALS" ]; then
          echo "❌ ОШИБКА: GOOGLE_SHEETS_CREDENTIALS не установлен в GitHub Secrets"
          echo "Добавьте GOOGLE_SHEETS_CREDENTIALS в Settings → Secrets and variables → Actions"
          exit 1
        fi
        
        if [ -z "$SPREADSHEET_ID" ]; then
          echo "❌ ОШИБКА: SPREADSHEET_ID не установлен в GitHub Secrets"
          echo "Добавьте SPREADSHEET_ID в Settings → Secrets and variables → Actions"
          exit 1
        fi
        
        # Проверяем финальные значения (скрываем токен)
        echo "BOT_TOKEN: ${BOT_TOKEN:0:10}..."
        echo "CHAT_ID: $CHAT_ID"
        echo "SPREADSHEET_ID: $SPREADSHEET_ID"
        echo "ANNOUNCEMENTS_TOPIC_ID: ${ANNOUNCEMENTS_TOPIC_ID:-26}"
        
        # Проверяем наличие Python скрипта
        if [ ! -f "run_training_polls.py" ]; then
          echo "❌ Файл run_training_polls.py не найден"
          exit 1
        fi
        
        echo "Запуск системы создания опросов тренировок..."
        python run_training_polls.py
        
    - name: Run Scheduled Data Collection
      env:
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        CHAT_ID: ${{ secrets.CHAT_ID }}
        GOOGLE_SHEETS_CREDENTIALS: ${{ secrets.GOOGLE_SHEETS_CREDENTIALS }}
        SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}
        ANNOUNCEMENTS_TOPIC_ID: ${{ secrets.ANNOUNCEMENTS_TOPIC_ID }}
      run: |
        # Проверяем наличие обязательных переменных
        if [ -z "$BOT_TOKEN" ]; then
          echo "❌ ОШИБКА: BOT_TOKEN не установлен в GitHub Secrets"
          echo "Добавьте BOT_TOKEN в Settings → Secrets and variables → Actions"
          exit 1
        fi
        
        if [ -z "$CHAT_ID" ]; then
          echo "❌ ОШИБКА: CHAT_ID не установлен в GitHub Secrets"
          echo "Добавьте CHAT_ID в Settings → Secrets and variables → Actions"
          exit 1
        fi
        
        if [ -z "$GOOGLE_SHEETS_CREDENTIALS" ]; then
          echo "❌ ОШИБКА: GOOGLE_SHEETS_CREDENTIALS не установлен в GitHub Secrets"
          echo "Добавьте GOOGLE_SHEETS_CREDENTIALS в Settings → Secrets and variables → Actions"
          exit 1
        fi
        
        if [ -z "$SPREADSHEET_ID" ]; then
          echo "❌ ОШИБКА: SPREADSHEET_ID не установлен в GitHub Secrets"
          echo "Добавьте SPREADSHEET_ID в Settings → Secrets and variables → Actions"
          exit 1
        fi
        
        # Проверяем наличие Python скрипта
        if [ ! -f "run_scheduled_collection.py" ]; then
          echo "❌ Файл run_scheduled_collection.py не найден"
          exit 1
        fi
        
        echo "Запуск сбора данных по расписанию..."
        python run_scheduled_collection.py
        
    - name: Handle errors
      if: failure()
      env:
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        CHAT_ID: ${{ secrets.CHAT_ID }}
      run: |
        echo "❌ GitHub Actions завершился с ошибкой"
        echo "Проверка доступности переменных для отправки уведомления об ошибке..."
        
        if [ -z "$BOT_TOKEN" ]; then
          echo "⚠️ BOT_TOKEN недоступен для отправки уведомления об ошибке"
          echo "Добавьте BOT_TOKEN в GitHub Secrets для получения уведомлений об ошибках"
        fi
        
        if [ -z "$CHAT_ID" ]; then
          echo "⚠️ CHAT_ID недоступен для отправки уведомления об ошибке"
          echo "Добавьте CHAT_ID в GitHub Secrets для получения уведомлений об ошибках"
        fi
        
        echo "Ошибки будут отправлены в основной чат через скрипт"
